apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-model-cache
  labels:
    app: vllm-qwen3-30b-fp8
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Ti
  storageClassName: nfs-client # Replace with your RWX-capable storage class

