apiVersion: apps/v1
kind: Deployment
metadata:
  name: langfuse
  labels:
    app: langfuse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langfuse
  template:
    metadata:
      labels:
        app: langfuse
    spec:
      containers:
        - name: langfuse
          image: ghcr.io/langfuse/langfuse:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: langfuse-secrets
          env:
            - name: DATABASE_URL
              valueFrom: { secretKeyRef: { name: langfuse-secrets, key: DATABASE_URL } }
            - name: NEXTAUTH_URL
              valueFrom: { secretKeyRef: { name: langfuse-secrets, key: NEXTAUTH_URL } }
            - name: NEXTAUTH_SECRET
              valueFrom: { secretKeyRef: { name: langfuse-secrets, key: NEXTAUTH_SECRET } }
            - name: ENCRYPTION_KEY
              valueFrom: { secretKeyRef: { name: langfuse-secrets, key: ENCRYPTION_KEY } }
            - name: LANGFUSE_ENABLE_DATABASE_MIGRATIONS
              value: "true"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet: { path: /api/public/health, port: 3000 }
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet: { path: /api/public/health, port: 3000 }
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: langfuse
spec:
  selector:
    app: langfuse
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: langfuse
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: langfuse.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: langfuse
                port:
                  number: 80
  tls:
    - hosts: ["langfuse.example.com"]
      secretName: langfuse-tls

